### ISSUE TITLE
[FR] CC字幕底边距以视频底边为准

### ISSUE THREAD

**Issue by zjns** [festoney8/bilibili-cleaner#132]
目前B站的CC字幕底边距是以屏幕底边为准偏移，导致在mac上大部分视频全屏时由于高度不能撑满屏幕而出现字幕一半架在视频上，很难看，所以询问是否有办法修改字幕底边距以视频底边为准。如图所示：
![QQ_1726201038357](https://github.com/user-attachments/assets/71cd7ca9-59ea-437c-8bcb-2cbd05851b59)

**Comment by festoney8** [comment]
看起来是非 16:9 屏幕全屏播放 16:9 视频的现象，请问网页全屏时也会这样吗？

**Comment by zjns** [comment]
一样也有这个问题，很久前给客服反馈，并没有什么卵用，所以才来此求助。
![QQ_1726223098198](https://github.com/user-attachments/assets/df61d28e-1bfc-4d44-8560-6a0b8c65964a)

**Comment by festoney8** [comment]
试一下用 Stylus 插件给播放页新增下方样式，数值可自行调节

```css
.bpx-player-container:is([data-screen="web"], [data-screen="full"]) .bpx-player-subtitle-panel-position[data-position=bottom] {
    bottom: 8% !important
}
```

**Comment by zjns** [comment]
感谢，可以调整字幕初始偏移了，但好像还是以页面底边为描点调整的，不同比例的视频全屏后相对位置还是不太一样

**Comment by festoney8** [comment]
> 感谢，可以调整字幕初始偏移了，但好像还是以页面底边为描点调整的，不同比例的视频全屏后相对位置还是不太一样

因为有的时视频上下贴紧浏览器，但有时可能是左右贴紧浏览器上下有黑边，所以会有差别

精细调节可以写成下方这样，从视频横向中轴开始计算位置

```css
/* 网页全屏 */
.bpx-player-container[data-screen="web"] .bpx-player-subtitle-panel-position[data-position=bottom] {
    bottom: calc(50% - 300px) !important;
}

/* 全屏 */
.bpx-player-container[data-screen="full"] .bpx-player-subtitle-panel-position[data-position=bottom] {
    bottom: calc(50% - 330px) !important;
}
```

**Comment by zjns** [comment]
emm 效果还是不太好，没有办法拿到当前视频内容的底边位置然后基于此偏移吗？

**Comment by festoney8** [comment]
JS 获取当前视频底边位置特别麻烦，要考虑页面变动之类，能用 CSS 解决尽可能不用 JS

试试这段样式，所有 16:9 的视频可以强制固定字幕位置在视频内，但 4:3 视频和 21:9 视频会出问题

```css
:root {
    --subtitle-bottom: 14px;
}
.bpx-player-container:is([data-screen="web"], [data-screen="full"]) .bpx-player-subtitle-panel-position[data-position=bottom] {
    bottom: calc(50% - 0.5 * min(100vw / 16 * 9, 100vh) + var(--subtitle-bottom)) !important;
}
```
