### ISSUE TITLE
隐藏横幅banner后，往下滚动时会跳一下

### ISSUE THREAD

**Issue by nothingshiru** [festoney8/bilibili-cleaner#144]
顶栏变化的瞬间，下面的内容就直接吸附上去了。
https://github.com/user-attachments/assets/5091fa29-d1e7-4bb5-8874-244f6f27d5c2

我现在这样隐藏横幅

```css
.bili-header__banner {
    min-height: unset !important;
    height: 64px !important;
    background: var(--bg1) !important;
    div {
        display: none !important;
    }
}

/* 底部分隔线 */
.bili-header__bar {
    box-shadow: inset 0 -1px 0 var(--line_regular) !important;
}

/* 文字、图标颜色 */
:is(.right-entry-icon,.right-entry-text,.entry-title,.default-entry,.zhuzhan-icon) {
    color: var(--v_text1) !important;
}
```
