### ISSUE TITLE
"修复 搜索框居中“似乎不起作用

### ISSUE THREAD

**Issue by nothingshiru** [festoney8/bilibili-cleaner#146]
在首页测试了位于顶部、下滑状态在不同窗口宽度下的样子。”修复 搜索框居中“开启或关闭，在下滑状态且页面宽度1100到1366.9之间时都不能居中搜索框，在其他状态下表现一致。

发现这条规则没有被干掉
```css
@media (min-width: 1100px) and (max-width: 1366.9px) {
  .bili-header .slide-down .center-search-container .center-search__bar {
      margin: 0 10px;
  }
}
```

我这样解决
```css
.center-search__bar {
    margin: 0 auto !important;
}
```
