### ISSUE TITLE
优化搜索框居中

### ISSUE THREAD

**Issue by nothingshiru** [festoney8/bilibili-cleaner#161]
因为顶栏左、右部分宽度不一样，搜索框目前只是在中间部分居中，而不是在顶栏居中。

可以让左、右部分一样宽，让搜索框真的居中
```css
.left-entry, .right-entry {
    flex: 1;
    min-width: max-content;
    margin: 0 !important;
}

.right-entry {
    justify-content: flex-end;
}

.bili-header .slide-down .center-search-container {
    margin: 0;
}
```
![屏幕截图(29)](https://github.com/user-attachments/assets/74b4bd11-453e-4f3c-ab7f-0138fc2063e3)
