### ISSUE TITLE
[FR] 搜索界面

### ISSUE THREAD

**Issue by polarlinda6** [festoney8/bilibili-cleaner#210]
### 功能描述

搜索界面
1. 是否可以将搜索框整合进顶栏呢
2. 希望增加去除搜索按钮的选项
![Image](https://github.com/user-attachments/assets/f6e0ca8d-7890-4d2a-ad7b-464039cc415f)

**Comment by festoney8** [comment]
这里本来就有一个隐藏起来的搜索栏，但搜索关键词不会同步显示在里面，让它显示出来只会反而会不好用，强制显示会很复杂而且有延迟，得不偿失

![Image](https://github.com/user-attachments/assets/26358e59-b7ef-4456-8d68-7138791a6d26)

---

隐藏搜索按钮可以安装 [Stylus](https://chromewebstore.google.com/detail/stylus/clngdbkpkpeebahjckkjfobafhncgmne) 插件，给搜索页新增下方样式，如图
```css
.search-input-wrap button {
    display: none !important;
}
.search-input-wrap .clear-icon {
    right: 15px !important;
}
.search-input-el {
    width: 100% !important;
}
```

![Image](https://github.com/user-attachments/assets/08ebfc78-52cd-468a-bae2-3aa11d7d0ad4)
