### ISSUE TITLE
[FR] 直播页面

### ISSUE THREAD

**Issue by polarlinda6** [festoney8/bilibili-cleaner#217]
### 功能描述

1.隐藏谁来了
2.隐藏 "哔哩升龙霸"
3.可以将所有名字变为蓝色
![Image](https://github.com/user-attachments/assets/18ae5c71-19f8-4457-aa92-badf2b1c48df)

**Comment by festoney8** [comment]
用户名颜色在禁用掉弹幕背景时可以区分舰长房主和普通用户，颜色一致就没意义了

可以自行使用如下 Stylus 样式修改用户名颜色，颜色可以自定义，如图

```css
.chat-history-list .chat-item.danmaku-item .user-name {
    color: #00D1F1 !important;
}
```

![Image](https://github.com/user-attachments/assets/278867fb-6ddc-48f7-b70d-886aab2af558)
---
XXX 来了和礼物消息元素转瞬即逝很难捕捉，若捕捉到会加入

**Comment by polarlinda6** [comment]
> .chat-history-list .chat-item.danmaku-item .user-name {
>     color: #00D1F1 !important;
> }

也对, 那话说可以给普通用户换成大会员色吗, 房主等还是原来的蓝色, 主要是昵称与发言一个颜色, 太难区分了

**Comment by festoney8** [comment]
隐藏信息栏问题、顶栏闪烁已复现，下一版修复

隐藏礼物栏失效未复现

---
修改普通用户名颜色使用下方样式，颜色可自行修改

```css
.chat-history-list .chat-item.danmaku-item .user-name:not([style]) {
    color: #FB7299 !important;
}
```
---

隐藏弹幕评论文字 + 隐藏发送按钮

```css
#live-player .chat-input::placeholder {
    color: transparent !important;
}
.send-danmaku {
    display: none !important;
}
```

---

隐藏 SC + 隐藏成为舰长消息

```css
.chat-item.superChat-card-detail {
    display: none !important;
}
.chat-item.guard-buy {
    display: none !important;
}
```

---

全屏滚动暂不考虑，直播页播放器下方内容不像播放页评论区，下拉需求不重要

---

火狐浏览器修改为默认播放声音
https://www.zhihu.com/question/440678342/answer/1976297311
