### ISSUE TITLE
[Other] 深色模式与自定义顶栏兼容

### ISSUE THREAD

**Issue by polarlinda6** [festoney8/bilibili-cleaner#242]
### 文字说明

开启深色模式，Bilibili Evolved 的自定义顶栏不会变色，这有什么阿好的兼容办法吗

![Image](https://github.com/user-attachments/assets/c26954da-f0ba-4e65-9c02-05e97a757479)

**Comment by festoney8** [comment]
只用 Bilibili Evolved 的夜间模式就可以了呀

**Comment by polarlinda6** [comment]
> 只用 Bilibili Evolved 的夜间模式就可以了呀

唉，主要是他那个夜间模式太差了，上面的是这个脚本的，下面的的是evolved的

![Image](https://github.com/user-attachments/assets/f0305ab1-b9dc-40bf-bf4b-3fabfff20f81)

![Image](https://github.com/user-attachments/assets/562b0f3e-0514-4455-883f-d829bcfc202e)

**Comment by festoney8** [comment]
Evolved 的夜间模式在样式优先级上会更高，这个没什么办法，如果有颜色不适可以再加一个 Stylus 插件改颜色

**Comment by polarlinda6** [comment]
emmm 大佬求教，插件规则怎么写呢，希望将他的两种灰色（上图），改成本脚本的这个颜色（下图）

![Image](https://github.com/user-attachments/assets/308d3b71-4d63-4353-99f9-4db11c7a1fd4)

![Image](https://github.com/user-attachments/assets/0a94d723-2178-4b81-a79b-3991ed771555)

**Comment by festoney8** [comment]
```css
.bili-dyn-my-info,
.bili-dyn-live-users,
.bili-dyn-publishing,
.bili-dyn-up-list,
.bili-dyn-list-tabs,
.bili-dyn-list-notification,
.bili-dyn-item,
.bili-dyn-list-empty,
.bili-dyn-list-loading,
.topic-panel,
.switch-tab {
    background-color: #242628 !important;
}
```

![Image](https://github.com/user-attachments/assets/2e2dbe07-0977-4e76-b105-e4021b8038b3)

**Comment by polarlinda6** [comment]
> .bili-dyn-my-info,
> .bili-dyn-live-users,
> .bili-dyn-publishing,
> .bili-dyn-up-list,
> .bili-dyn-list-tabs,
> .bili-dyn-list-notification,
> .bili-dyn-item,
> .bili-dyn-list-empty,
> .bili-dyn-list-loading,
> .topic-panel,
> .switch-tab {
>     background-color: #242628 !important;
> }
> ![Image](https://github.com/user-attachments/assets/2e2dbe07-0977-4e76-b105-e4021b8038b3)

感谢完美，但大佬能否将视频卡片的颜色也改成这个呢

![Image](https://github.com/user-attachments/assets/7b7118d2-10e2-4346-9770-f8935410b28d)

**Comment by festoney8** [comment]
```css
.bili-dyn-my-info,
.bili-dyn-live-users,
.bili-dyn-publishing,
.bili-dyn-up-list,
.bili-dyn-list-tabs,
.bili-dyn-list-notification,
.bili-dyn-item,
#app .bili-dyn-card-video__body,
.bili-dyn-list-empty,
.bili-dyn-list-loading,
.topic-panel,
.switch-tab {
    background-color: #242628 !important;
}
```
