### ISSUE TITLE
[BUG] 直播间网页全屏右上角显示错误

### ISSUE THREAD

**Issue by River-2024** [festoney8/bilibili-cleaner#248]
### 出问题的页面

直播页

### 问题功能名

未知

### 问题描述

直播间网页全屏时，右上角显示错误

### 上传截图（可选）

非网页全屏时右上角
![Image](https://github.com/user-attachments/assets/2fc096a6-d4e8-4e5e-a868-6d58d4662b4a)

网页全屏时右上角

![Image](https://github.com/user-attachments/assets/fa4d4505-a759-4127-97e0-c9cb81ed40ef)

插件设置
![Image](https://github.com/user-attachments/assets/043ea0cb-4e19-4b82-9674-f7cc8f7a6381)

### 操作系统

Windows11

### 浏览器版本

EDGE 版本 137.0.3296.52 (正式版本) (64 位)

### 脚本管理器版本

v5.3.3 Tampermonkey 

### 本插件版本

v4.3.1

### 可稳定复现问题

是

### 在暴力猴/篡改猴内，只启用本脚本时，仍出现问题

是

### 禁用掉对 B 站生效的其他浏览器插件（不含暴力猴/篡改猴），仍出现问题

是

**Comment by festoney8** [comment]
试了一下，在我的插件里新增修改全站字体功能稳定性较差，会在刷新时出现字体闪现的现象，体验不好

推荐使用 Stylus 手动修改字体，更稳定，方法如下

安装 [Stylus](https://chromewebstore.google.com/detail/stylus/clngdbkpkpeebahjckkjfobafhncgmne) 插件，新增下方样式，修改样式中的字体名称，其他配置如图

```css
:not(
    .bili-danmaku-x-dm,
    .bili-danmaku-x-high-text,
    .bpx-player-subtitle-panel-text,
    .bili-subtitle-x-subtitle-panel-text
) {
    font-family: 你的字体 !important;
}
```

![Image](https://github.com/user-attachments/assets/dd6320ce-b251-4003-a664-4afa6d5cc65e)
